//! beamfs-bench pipeline -- MIL no-NAK validation chain.
//!
//! Phases executed before any test runs:
//!   0.1 `verify_clean_working_trees`   3 git repos must be clean
//!   0.2 `verify_lockstep_sources`      sha256 manifest source vs yocto layer
//!   0.3 `bitbake_image`                build canonical .beamfs
//!   0.4 `extract_reference_ko_sha`     loop-mount canonical, sha256 module
//!   0.5 `redeploy_4_vms`               virsh destroy + cp x4 + chown + start
//!   0.6 `wait_ssh_ready_parallel`      reuse lifecycle helper
//!   0.7 `verify_module_identity`       sha256 in-VM == reference, on 4 nodes
//!
//! Phases executed after tests:
//!   8.1 `verify_dmesg_clean`           no BUG/Oops/WARN on any node
//!   8.2 `emit_manifest`                JSON + GPG-detached-sign
//!
//! All phases fail-closed. Any non-zero exit aborts the pipeline,
//! emits a partial manifest with the failure record, and returns rc=2.

use anyhow::{anyhow, bail, Context, Result};
use chrono::Utc;
use serde::Serialize;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// Every file that goes into the kernel, not a list written once.
///
/// The list held twelve names while the tree grew to twenty-two, and
/// the ten it missed included indirparity.c and beamfs_format.h -- the
/// two files the 2026-09-11 session changed most. A divergence in
/// either would have passed the check that exists to catch exactly
/// that.
///
/// Read from the directory rather than enumerated, so a file added to
/// the filesystem is checked from the moment it exists.
fn kernel_sources() -> Result<Vec<String>> {
    let mut out: Vec<String> = Vec::new();

    for entry in std::fs::read_dir(crate::lab::beamfs_repo())
        .with_context(|| format!("read {}", crate::lab::beamfs_repo()))?
    {
        let name = entry?.file_name().to_string_lossy().into_owned();
        let keep = name.ends_with(".c")
            || name.ends_with(".h")
            || name == "Makefile"
            || name == "Kconfig"
            || name == "COPYING";
        // beamfs.mod.c is generated by the build, not source.
        if keep && name != "beamfs.mod.c" {
            out.push(name);
        }
    }
    out.sort();
    if out.is_empty() {
        bail!("no kernel sources found in {}", crate::lab::beamfs_repo());
    }
    Ok(out)
}

/// Files that live in the yocto layer and nowhere else.
///
/// mkfs.beamfs.c and the decoder it links are not in the beamfs repo,
/// so the lockstep check cannot compare them -- but they are part of
/// what a run measures and belong in the manifest.
const YOCTO_ONLY_SOURCES: &[&str] = &[
    "mkfs.beamfs.c", "rs_decode.c", "rs_decode.h", "rs_decode_internal.h",
];


const VM_NAMES: &[&str] = &["beamfs-master", "beamfs-compute01", "beamfs-compute02", "beamfs-compute03"];
const VM_IPS:   &[&str] = &["192.168.56.10", "192.168.56.11", "192.168.56.12", "192.168.56.13"];

#[derive(Debug, Clone, Serialize)]
pub struct PipelineManifest {
    pub started_at:        String,
    pub finished_at:       String,
    pub commit_beamfs:     String,
    pub commit_yocto:      String,
    pub commit_bench:      String,
    pub source_sha256:     Vec<(String, String)>,
    pub canonical_beamfs_sha256: String,
    /// "Matched" or "Ignored". Empty when the phase did not run.
    pub chain_verdict:     String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub chain_seal:        Option<crate::chain::Seal>,
    pub reference_image_sha256:   String,
    pub in_vm_kernel_stamp:   Vec<(String, String)>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub resolved_vda_paths: BTreeMap<String, String>,
    pub phases:            Vec<(String, String, i32)>,
    pub overall_rc:        i32,
}

fn sha256_file(path: &Path) -> Result<String> {
    let out = Command::new("sha256sum").arg(path).output()
        .with_context(|| format!("sha256sum {}", path.display()))?;
    if !out.status.success() {
        bail!("sha256sum failed on {}: {}", path.display(), String::from_utf8_lossy(&out.stderr));
    }
    let s = String::from_utf8_lossy(&out.stdout);
    Ok(s.split_whitespace().next().unwrap_or("").to_string())
}

fn git_head_sha(repo: &str) -> Result<String> {
    let out = Command::new("git").args(["-C", repo, "rev-parse", "HEAD"]).output()
        .with_context(|| format!("git rev-parse HEAD in {repo}"))?;
    if !out.status.success() {
        bail!("git rev-parse failed in {repo}: {}", String::from_utf8_lossy(&out.stderr));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn ssh_exec(ip: &str, cmd: &str) -> Result<String> {
    let out = Command::new("ssh")
        .args(["-T", "-i", crate::lab::ssh_key(), "-o", "StrictHostKeyChecking=no",
               "-o", "ConnectTimeout=10", "-o", "BatchMode=yes",
               &format!("hpcadmin@{ip}"), cmd])
        .stdin(Stdio::null())
        .output()
        .with_context(|| format!("ssh {ip}"))?;
    if !out.status.success() {
        bail!("ssh {ip} failed: {}", String::from_utf8_lossy(&out.stderr));
    }
    Ok(String::from_utf8_lossy(&out.stdout).to_string())
}

// ---------------------------------------------------------------------
// Phase 0.1
// ---------------------------------------------------------------------
pub fn verify_clean_working_trees() -> Result<()> {
    println!("[pipeline 0.1] verify clean working trees on 2 lockstep repos");
    // R19 semantics: lockstep is between beamfs and yocto-beamfs (kernel sources
    // must be byte-identical between the two repos). beamfs-bench is the bench
    // tool itself; it is intentionally excluded so that bench refactors can
    // run their own validation chain without requiring a self-commit first.
    for repo in &[crate::lab::beamfs_repo(), crate::lab::yocto_repo()] {
        let out = Command::new("git").args(["-C", repo, "status", "-s"]).output()
            .with_context(|| format!("git status in {repo}"))?;
        let dirty = String::from_utf8_lossy(&out.stdout);
        if !dirty.trim().is_empty() {
            bail!("repo {repo} not clean:\n{dirty}");
        }
        println!("  {repo} clean");
    }
    // beamfs-bench check downgraded from blocking to informative WARN.
    {
        let out = Command::new("git").args(["-C", crate::lab::bench_repo(), "status", "-s"]).output()
            .with_context(|| format!("git status in {}", crate::lab::bench_repo()))?;
        let dirty = String::from_utf8_lossy(&out.stdout);
        if dirty.trim().is_empty() {
            println!("  {} clean", crate::lab::bench_repo());
        } else {
            println!("  {} dirty (informative, non-blocking):", crate::lab::bench_repo());
            for line in dirty.lines().take(20) {
                println!("    {line}");
            }
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------
// Phase 0.2
// ---------------------------------------------------------------------
pub fn verify_lockstep_sources() -> Result<Vec<(String, String)>> {
    let sources = kernel_sources()?;
    println!("[pipeline 0.2] verify lockstep sources ({} files)", sources.len());

    let mut manifest = Vec::new();
    for f in &sources {
        let p1 = PathBuf::from(crate::lab::beamfs_repo()).join(f);
        let p2 = PathBuf::from(crate::lab::yocto_kernel_files()).join(f);
        let s1 = sha256_file(&p1).with_context(|| format!("hash beamfs/{f}"))?;
        // A source present in beamfs and absent from the layer is a
        // divergence of the worst kind: the build takes what the layer
        // has, so the file simply is not compiled.
        let s2 = sha256_file(&p2)
            .with_context(|| format!("{f} is in beamfs and not in the yocto layer"))?;
        if s1 != s2 {
            bail!("lockstep DIVERGENCE: {f}\n  beamfs: {s1}\n  yocto:  {s2}");
        }
        manifest.push((f.clone(), s1));
    }
    println!("  {} files byte-identical", sources.len());

    // Hashed but not compared: these have one copy, in the layer.
    for f in YOCTO_ONLY_SOURCES {
        let p = PathBuf::from(crate::lab::yocto_kernel_files()).join(f);
        if p.exists() {
            manifest.push((format!("yocto:{f}"), sha256_file(&p)?));
        }
    }
    Ok(manifest)
}

// ---------------------------------------------------------------------
// Phase 0.3
// ---------------------------------------------------------------------
pub fn bitbake_image(skip: bool) -> Result<()> {
    bitbake_image_to(skip, None)
}

/// Same as `bitbake_image` but optionally captures stdout+stderr to a log file
/// (in addition to streaming to terminal). Used by mega scope to archive build logs.
pub fn bitbake_image_to(skip: bool, log_dir: Option<&Path>) -> Result<()> {
    if skip {
        println!("[pipeline 0.3] bitbake SKIPPED (--skip-bitbake)");
        return Ok(());
    }
    let image = crate::lab::image_name();
    println!("[pipeline 0.3] bitbake {image} (streaming)");
    let mut cmd = format!(
        "cd {poky} && source oe-init-build-env {build} > /dev/null 2>&1 && \
         bitbake {image} 2>&1",
        poky = crate::lab::poky_dir(),
        build = crate::lab::build_dir_name(),
    );
    if let Some(dir) = log_dir {
        std::fs::create_dir_all(dir).context("create bitbake log dir")?;
        let log_path = dir.join("bitbake-stdout.log");
        // tee: keep streaming visible AND capture to file.
        cmd = format!("({cmd}) | tee {}", log_path.display());
    }
    let home_env = format!(
        "HOME={}",
        std::env::var("HOME").unwrap_or_else(|_| "/home/aurelien".to_string())
    );
    let status = Command::new("env")
        .args(["-i", &home_env, "TERM=xterm",
               "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
               "bash", "-c", &cmd])
        .status()
        .context("bitbake spawn")?;
    if !status.success() {
        bail!("bitbake {image} failed (exit {:?})", status.code());
    }
    let p = PathBuf::from(crate::lab::canonical_image());
    if !p.exists() {
        bail!("canonical beamfs not produced: {}", p.display());
    }
    println!("  canonical beamfs produced: {}", p.display());
    Ok(())
}

// ---------------------------------------------------------------------
// Phase 0.4
// ---------------------------------------------------------------------
/// The hash of the image the nodes will boot.
///
/// This used to also dig a beamfs.ko out of the rootfs build directory
/// and hash it, for a check that compared it against each node. The
/// filesystem is builtin -- CONFIG_BEAMFS_FS=y -- so that .ko is
/// installed by the build and loaded by nobody; hashing it said nothing
/// about the running kernel.
///
/// What matters is the image, and redeploy_4_vms verifies it lands on
/// every node byte for byte.
pub fn canonical_image_sha() -> Result<String> {
    println!("[pipeline 0.4] hash the canonical image");
    let beamfs_sha = sha256_file(Path::new(crate::lab::canonical_image()))
        .context("hash canonical .beamfs")?;
    println!("  canonical beamfs sha256: {beamfs_sha}");
    Ok(beamfs_sha)
}

// ---------------------------------------------------------------------
// Phase 0.4bis -- the chain seal.
// BX deploys first and writes down which image it measured. This bench
// is the second half of that campaign or it is not part of it; see
// chain.rs for what the 2026-09-19 run cost.
// ---------------------------------------------------------------------
/// Check the canonical image against the seal beamfs-xfstests left.
///
/// # Errors
/// When no seal exists or it names another image, unless
/// `BEAMFS_CHAIN_IGNORE` is set.
pub fn verify_chain_seal(
    canonical_sha: &str,
) -> Result<(crate::chain::Verdict, Option<crate::chain::Seal>)> {
    println!("[pipeline 0.4bis] verify the chain seal left by beamfs-xfstests");
    crate::chain::verify(canonical_sha, Path::new(crate::lab::canonical_image()))
}

// ---------------------------------------------------------------------
// Phase 0.0 -- R21 isolation architecture invariant.
// Wrapper around lifecycle::assert_isolation_architecture so callers
// see Phase 0.0 in logs and the manifest.
// ---------------------------------------------------------------------
pub fn assert_isolation_r21() -> Result<()> {
    println!("[pipeline 0.0] verify R21 cluster isolation architecture");
    crate::lifecycle::assert_isolation_architecture()
        .context("R21 isolation pre-flight failed")
}

// ---------------------------------------------------------------------
// Phase 0.5 -- redeploy + cluster up.
// Reuses lifecycle helpers (define_missing_vms, destroy_all_vms,
// start_network, start_all_vms) so the R21-validated invariants of
// those helpers remain in force; this function only adds the cp/chown
// step between destroy and start.
// ---------------------------------------------------------------------
/// Resolve the actual host-side file path backing the vda device of `vm`
/// by parsing `virsh dumpxml`. Protects against silent drift in the
/// libvirt naming convention (cf. Bug B 2026-05-15: master.xml had vda
/// pointing to beamfs-master-research.beamfs while the pipeline assumed
/// beamfs-master.beamfs; Phase 0.5 cp landed in the void).
///
/// Looks specifically for: <disk type='file' device='disk'> with
/// <target dev='vda' bus='virtio'/> and returns <source file='...'>.
pub fn resolve_vda_source(vm_name: &str) -> Result<String> {
    let output = Command::new("sudo")
        .args(["virsh", "-c", "qemu:///system", "dumpxml", vm_name])
        .output()
        .with_context(|| format!("spawn sudo virsh dumpxml {vm_name}"))?;
    if !output.status.success() {
        bail!(
            "sudo virsh dumpxml {vm_name} failed (exit {:?}): {}",
            output.status.code(),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    let xml = String::from_utf8(output.stdout)
        .context("virsh dumpxml stdout is not UTF-8")?;
    let doc = roxmltree::Document::parse(&xml)
        .with_context(|| format!("parse virsh dumpxml output for {vm_name}"))?;

    for disk in doc.descendants().filter(|n| n.has_tag_name("disk")) {
        let disk_type   = disk.attribute("type").unwrap_or("");
        let device_kind = disk.attribute("device").unwrap_or("");
        if disk_type != "file" || device_kind != "disk" {
            continue;
        }
        let target = disk.children().find(|n| n.has_tag_name("target"));
        let source = disk.children().find(|n| n.has_tag_name("source"));
        let (Some(target), Some(source)) = (target, source) else {
            continue;
        };
        if target.attribute("dev").unwrap_or("") != "vda" {
            continue;
        }
        if target.attribute("bus").unwrap_or("") != "virtio" {
            continue;
        }
        let src_file = source.attribute("file")
            .ok_or_else(|| anyhow::anyhow!("vm {vm_name}: <disk vda> has no <source file=>"))?;
        return Ok(src_file.to_string());
    }
    bail!("vm {vm_name}: no <disk type='file' device='disk'> with vda target found in dumpxml")
}

pub fn redeploy_4_vms() -> Result<BTreeMap<String, String>> {
    println!("[pipeline 0.5] redeploy 4 VMs from canonical .beamfs");

    crate::lifecycle::define_missing_vms()
        .context("define missing VMs (cold-start safety)")?;

    // R31 step 0.5a: resolve each VM's actual vda backing path from
    // libvirt XML BEFORE destroy. Pins the cp target to whatever libvirt
    // is actually configured to use, instead of assuming <vm>.beamfs.
    let mut resolved: BTreeMap<String, String> = BTreeMap::new();
    for vm in VM_NAMES {
        let path = resolve_vda_source(vm)
            .with_context(|| format!("resolve vda source for {vm}"))?;
        println!("  {vm} : resolved vda source = {path}");
        resolved.insert((*vm).to_string(), path);
    }

    crate::lifecycle::destroy_all_vms();

    // R31 step 0.5b: confirm no qemu process is still holding a FD on
    // any target file. `fuser -s <path>` returns 0 if any FD found, 1
    // if none. We want rc=1 (none). exit 0 means a process still holds
    // the FD, which would corrupt cp.
    let _ = Command::new("sync").status();
    for vm in VM_NAMES {
        let path = &resolved[*vm];
        let st = Command::new("sudo")
            .args(["fuser", "-s", path])
            .status()
            .with_context(|| format!("fuser {path}"))?;
        if st.success() {
            bail!("redeploy: a process still holds a FD on {path} (virsh destroy did not release; check `sudo fuser {path}` manually)");
        }
        println!("  {vm} : FDs released on {path}");
    }

    let _ = Command::new("sync").status();

    let canonical_sha = sha256_file(Path::new(crate::lab::canonical_image()))
        .context("hash canonical .beamfs")?;
    println!("  canonical .beamfs sha256: {canonical_sha}");

    for vm in VM_NAMES {
        let dst = &resolved[*vm];
        let st = Command::new("sudo")
            .args(["cp", crate::lab::canonical_image(), dst])
            .status().with_context(|| format!("cp beamfs -> {dst}"))?;
        if !st.success() { bail!("cp failed for {dst}"); }
        let st = Command::new("sudo")
            .args(["chown", "qemu:qemu", dst]).status()
            .with_context(|| format!("chown {dst}"))?;
        if !st.success() { bail!("chown failed for {dst}"); }

        let _ = Command::new("sync").status();
        let dst_sha = sha256_file(Path::new(dst))
            .with_context(|| format!("hash {dst}"))?;
        if dst_sha != canonical_sha {
            bail!(
                "redeploy verify FAIL for {dst}: deployed sha256={dst_sha} != canonical={canonical_sha} (R31: a stale VM held a FD on this file, or cp was interrupted; ensure no out-of-pipeline VM is running and rerun)"
            );
        }
        println!("  {vm} -> {dst} sha256 verified");
    }

    crate::lifecycle::start_network()
        .context("start hpcnet network")?;
    crate::lifecycle::start_all_vms()
        .context("start all 4 VMs")?;

    Ok(resolved)
}

// ---------------------------------------------------------------------
// Phase 0.7
// ---------------------------------------------------------------------
/// Confirm each node is running the beamfs that was built.
///
/// This used to hash /lib/modules/<kver>/updates/beamfs.ko on every
/// node and compare it to the one in the rootfs build directory. That
/// stopped meaning anything when the filesystem became builtin:
/// CONFIG_BEAMFS_FS=y, beamfs is listed in modules.builtin, lsmod shows
/// nothing -- and the .ko is still installed by the build, never loaded
/// by anyone. The check hashed a dead file and passed, whatever the
/// kernel was actually executing. A green light on the wrong evidence
/// is worse than no light.
///
/// What identifies the running code is the image the node booted, and
/// redeploy_4_vms already verifies that byte for byte against the
/// canonical .beamfs before the nodes start. What is left to confirm
/// here is that the node came up on it, which is what the kernel build
/// stamp in /proc/version says: it changes with every kernel build, so
/// two nodes agreeing on it agree on the kernel, and disagreeing with
/// the host's build means a node booted something else.
pub fn verify_kernel_identity_in_vm() -> Result<Vec<(String, String)>> {
    println!("[pipeline 0.7] verify the kernel build stamp on 4 nodes");
    let mut stamps = Vec::new();
    let mut first: Option<String> = None;

    for (i, ip) in VM_IPS.iter().enumerate() {
        let out = ssh_exec(ip, "cat /proc/version")
            .with_context(|| format!("ssh {ip} /proc/version"))?;
        let stamp = out.trim().to_string();

        // beamfs has to be in this kernel, not beside it.
        // The path in modules.builtin is kernel/fs/beamfs/beamfs.ko, not
        // fs/beamfs: anchoring at the start matched nothing and failed
        // a cluster that was correctly built.
        let builtin = ssh_exec(ip, "grep -c '/beamfs/' /lib/modules/$(uname -r)/modules.builtin || true")
            .unwrap_or_default();
        if builtin.trim() == "0" {
            bail!("{} ({ip}): beamfs is not builtin in the running kernel",
                  VM_NAMES[i]);
        }

        match &first {
            None => first = Some(stamp.clone()),
            Some(f) if *f != stamp => {
                bail!("kernel skew: {} ({ip}) booted\n  {stamp}\nwhile {} booted\n  {f}",
                      VM_NAMES[i], VM_NAMES[0]);
            }
            _ => {}
        }

        stamps.push((VM_NAMES[i].to_string(), stamp));
        println!("  {} ({ip}) builtin, same build as {}", VM_NAMES[i], VM_NAMES[0]);
    }
    Ok(stamps)
}

// ---------------------------------------------------------------------
// Phase 8.1
// ---------------------------------------------------------------------
pub fn verify_dmesg_clean() -> Result<()> {
    println!("[pipeline 8.1] verify dmesg clean on 4 nodes");
    let pat = "BUG\\|Oops\\|general protection\\|Kernel panic\\|stack-protector";
    let mut total = 0usize;
    for (i, ip) in VM_IPS.iter().enumerate() {
        let cmd = format!("sudo dmesg | grep -E -c '{pat}' || true");
        let out = ssh_exec(ip, &cmd)?;
        let n: usize = out.trim().parse().unwrap_or(0);
        if n > 0 {
            let detail = ssh_exec(ip, &format!("sudo dmesg | grep -E '{pat}' | head -20"))?;
            bail!("dmesg DIRTY on {} ({ip}): {n} matches\n{detail}",
                  VM_NAMES[i]);
        }
        total += n;
        println!("  {} ({ip}) clean", VM_NAMES[i]);
    }
    println!("  total kernel crash markers: {total}");
    Ok(())
}

// ---------------------------------------------------------------------
// Phase 8.2
// ---------------------------------------------------------------------
/// How long gpg is given to sign a manifest.
const SIGN_TIMEOUT: std::time::Duration = std::time::Duration::from_mins(2);

/// Whether gpg-agent holds a key it can sign with, without asking.
///
/// The question session priming asks at start, asked again here: the
/// cache has a lifetime of its own (max-cache-ttl), and a pipeline that
/// started with the key cached can end after it has expired.
fn gpg_key_cached() -> bool {
    Command::new("gpg-connect-agent")
        .args(["KEYINFO --list", "/bye"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .is_some_and(|o| {
            String::from_utf8_lossy(&o.stdout).lines().any(|l| {
                let t: Vec<&str> = l.split_whitespace().collect();
                l.starts_with("S KEYINFO ") && t.len() >= 7 && t[6] == "1"
            })
        })
}

/// Sign `path` into `<path>.asc` with `gpg` (the program and its leading
/// arguments), within `timeout`.
///
/// The signature is written to `<path>.asc.part` and renamed once gpg has
/// succeeded. On a refusal or a timeout gpg is killed and nothing is
/// left beside the manifest.
fn sign_manifest(gpg: &[&str], path: &std::path::Path, timeout: std::time::Duration)
    -> std::result::Result<PathBuf, String>
{
    let asc = PathBuf::from(format!("{}.asc", path.display()));
    let part = PathBuf::from(format!("{}.asc.part", path.display()));
    let _ = std::fs::remove_file(&part);
    let (prog, lead) = gpg.split_first().ok_or("no signing program")?;
    let mut child = Command::new(prog)
        .args(lead)
        .args(["--batch", "--pinentry-mode", "loopback",
               "--detach-sign", "--armor", "--yes", "--output"])
        .arg(&part)
        .arg(path)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("{prog} did not start: {e}"))?;
    let t0 = std::time::Instant::now();
    let status = loop {
        match child.try_wait() {
            Ok(Some(s)) => break s,
            Ok(None) if t0.elapsed() < timeout => {
                std::thread::sleep(std::time::Duration::from_millis(100));
            }
            Ok(None) => {
                let _ = child.kill();
                let _ = child.wait();
                let _ = std::fs::remove_file(&part);
                return Err(format!("{prog} did not finish within {}s and was killed",
                                   timeout.as_secs()));
            }
            Err(e) => {
                let _ = child.kill();
                let _ = child.wait();
                let _ = std::fs::remove_file(&part);
                return Err(format!("waiting for {prog}: {e}"));
            }
        }
    };
    let mut said = String::new();
    if let Some(mut err) = child.stderr.take() {
        let _ = std::io::Read::read_to_string(&mut err, &mut said);
    }
    if !status.success() {
        let _ = std::fs::remove_file(&part);
        return Err(format!("{prog} exited with {status}: {}", said.trim()));
    }
    std::fs::rename(&part, &asc).map_err(|e| format!("rename {}: {e}", part.display()))?;
    Ok(asc)
}

pub fn emit_manifest(m: &PipelineManifest) -> Result<PathBuf> {
    let stamp = Utc::now().format("%Y%m%dT%H%M%SZ").to_string();
    let path = PathBuf::from(format!("{}/manifest-{stamp}.json", crate::lab::runs_dir()));
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    let json = serde_json::to_string_pretty(m).context("serialize manifest")?;
    std::fs::write(&path, &json).with_context(|| format!("write {}", path.display()))?;
    println!("[pipeline 8.2] manifest written: {}", path.display());

    /*
     * Signed only when a key can sign with nobody at the keyboard, and
     * never for longer than SIGN_TIMEOUT.
     *
     * On 2026-10-01 a `full --auto-confirm` that had run for hours got
     * here with gpg-agent's cache empty: gpg said "Sorry, we are in
     * batchmode - can't get input" and did not exit, the pipeline waited
     * on it for forty minutes until it was killed, and a 0-byte .asc was
     * left beside the manifest. The manifest itself is the measurement
     * and is kept either way; the signature can be added afterwards.
     */
    if gpg_key_cached() {
        match sign_manifest(&["gpg"], &path, SIGN_TIMEOUT) {
            Ok(asc) => println!("  manifest GPG-signed: {}", asc.display()),
            Err(e) => {
                eprintln!("  WARNING: manifest NOT signed: {e}; sign it with");
                eprintln!("    gpg --detach-sign --armor {}", path.display());
            }
        }
    } else {
        eprintln!("  manifest NOT signed: no key in gpg-agent's cache; sign it with");
        eprintln!("    gpg --detach-sign --armor {}", path.display());
    }
    Ok(path)
}

pub fn now_iso() -> String { Utc::now().to_rfc3339() }

pub fn build_initial_manifest() -> Result<PipelineManifest> {
    Ok(PipelineManifest {
        started_at:  now_iso(),
        finished_at: String::new(),
        commit_beamfs: git_head_sha(crate::lab::beamfs_repo())?,
        commit_yocto:  git_head_sha(crate::lab::yocto_repo())?,
        commit_bench:  git_head_sha(crate::lab::bench_repo())?,
        source_sha256: Vec::new(),
        resolved_vda_paths: BTreeMap::new(),
        canonical_beamfs_sha256: String::new(),
        chain_verdict: String::new(),
        chain_seal:    None,
        reference_image_sha256:   String::new(),
        in_vm_kernel_stamp:       Vec::new(),
        phases:                Vec::new(),
        overall_rc:            -1,
    })
}

pub fn record(m: &mut PipelineManifest, name: &str, rc: i32) {
    m.phases.push((name.to_string(), now_iso(), rc));
}

pub fn fail(m: &mut PipelineManifest, name: &str, e: &anyhow::Error) -> anyhow::Error {
    record(m, name, 2);
    m.overall_rc  = 2;
    m.finished_at = now_iso();
    let _ = emit_manifest(m);
    anyhow!("pipeline phase {name} FAILED: {e:#}")
}

#[cfg(test)]
mod sign_tests {
    use super::sign_manifest;
    use std::time::{Duration, Instant};

    fn scratch(name: &str, script: &str) -> (std::path::PathBuf, std::path::PathBuf) {
        let d = std::env::temp_dir().join(format!("bb-sign-{}-{name}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).expect("scratch dir");
        std::fs::write(d.join("gpg.sh"), script).expect("fake gpg");
        let m = d.join("manifest.json");
        std::fs::write(&m, "{}\n").expect("manifest");
        (d, m)
    }

    fn gpg(d: &std::path::Path) -> String {
        d.join("gpg.sh").to_string_lossy().into_owned()
    }

    #[test]
    fn a_signature_lands_whole() {
        let (d, m) = scratch("ok", "while [ $# -gt 1 ]; do [ \"$1\" = --output ] && out=$2; shift; done\necho sig > \"$out\"\n");
        let g = gpg(&d);
        let asc = sign_manifest(&["sh", &g], &m, Duration::from_secs(20)).expect("signed");
        assert_eq!(asc, d.join("manifest.json.asc"));
        assert!(asc.exists());
        assert!(!d.join("manifest.json.asc.part").exists());
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn a_refusal_leaves_nothing() {
        // What gpg said on 2026-10-01, before it stopped answering.
        let (d, m) = scratch("refused", "echo \"gpg: Sorry, we are in batchmode - can't get input\" >&2\nexit 2\n");
        let g = gpg(&d);
        let e = sign_manifest(&["sh", &g], &m, Duration::from_secs(20)).expect_err("refused");
        assert!(e.contains("can't get input"), "{e}");
        assert!(!d.join("manifest.json.asc").exists());
        assert!(!d.join("manifest.json.asc.part").exists());
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn a_gpg_that_never_answers_is_killed() {
        let (d, m) = scratch("hang", "exec sleep 30\n");
        let g = gpg(&d);
        let t0 = Instant::now();
        let e = sign_manifest(&["sh", &g], &m, Duration::from_secs(1)).expect_err("killed");
        assert!(e.contains("did not finish"), "{e}");
        assert!(t0.elapsed() < Duration::from_secs(10));
        assert!(!d.join("manifest.json.asc").exists());
        assert!(!d.join("manifest.json.asc.part").exists());
        let _ = std::fs::remove_dir_all(&d);
    }
}
